# Use postgres/example user/password credentials
version: '3.1'

services:
  beer-api:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      CURRENCY_LAYER_TOKEN: <YOUR-API-TOKEN>
  db:
    image: postgres:14.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql